<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="home-PC" ignored="2" name="Default test(failed)" tests="11" failures="1" timestamp="09 Apr 2020 07:08:35 GMT" time="0.17" errors="0">
  <testcase name="test2" time="0.022" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.005" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.acc.Testng.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="org.acc.Testng.A">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at org.acc.Testng.A.test2(A.java:16)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.0" classname="org.acc.Testng.A">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase name="test3" time="0.0" classname="org.acc.Testng.A">
    <ignored/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Default test(failed) -->
